logging:
  level:
    ROOT: info
    org.hibernate.SQL: INFO
    com.hicham.airbnb_clone_back: INFO

spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/airbnb
    username: postgres
    password: root
    driver-class-name : org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        default_schema: airbnb_clone
  flyway:
    contexts: prod
    default-schema: airbnb_clone
